# Generated by Django 5.1.3 on 2026-05-12 11:09

import django.db.models.deletion
import blokus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_code",
                    models.CharField(
                        db_index=True,
                        default=blokus.models.generate_room_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("solo", "1-Player Solo"),
                            ("local2", "2-Player Local Pass-and-Play"),
                            ("online4", "4-Player Online"),
                        ],
                        default="local2",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for Players"),
                            ("active", "In Progress"),
                            ("finished", "Game Over"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_turn", models.IntegerField(default=0)),
                ("active_players", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.JSONField(default=list)),
                ("pieces_remaining", models.JSONField(default=dict)),
                ("move_history", models.JSONField(default=list)),
                ("passed_players", models.JSONField(default=list)),
                ("scores", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_state",
                        to="blokus.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("colors", models.JSONField(default=list)),
                ("seat", models.IntegerField(default=0)),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="blokus.room",
                    ),
                ),
            ],
            options={
                "ordering": ["seat"],
                "unique_together": {("room", "seat")},
            },
        ),
    ]
