# Generated by Django 6.0.5 on 2026-05-11 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Scattegories', max_length=100)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('complete', 'Complete')], default='setup', max_length=20)),
                ('current_round_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_games', to='players.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('locked', 'Locked'), ('reviewing', 'Reviewing'), ('complete', 'Complete')], default='waiting', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('timer_seconds', models.IntegerField(default=90)),
                ('current_review_question', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game_core.game')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('game', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('prompt', models.CharField(max_length=200)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game_core.round')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('round', 'index')},
            },
        ),
    ]
