# Generated by Django 6.0.5 on 2026-05-11 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_core', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_answer', models.CharField(blank=True, max_length=200)),
                ('normalised_answer', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='players.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game_core.question')),
            ],
            options={
                'ordering': ['player__display_name'],
                'unique_together': {('player', 'question')},
            },
        ),
        migrations.CreateModel(
            name='AnswerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_duplicate', models.BooleanField(default=False)),
                ('final_score', models.IntegerField(default=0)),
                ('decided_by_host', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='answers.answer')),
            ],
        ),
        migrations.CreateModel(
            name='JuryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('context_label', models.CharField(blank=True, max_length=200)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_votes', to='players.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_votes', to='game_core.round')),
            ],
            options={
                'unique_together': {('round', 'player', 'context_label')},
            },
        ),
    ]
