# Generated by Django 5.1.3 on 2026-04-05 12:21

import knightstrap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=knightstrap.models.make_room_code,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("p1_color", models.CharField(blank=True, default="", max_length=20)),
                ("p2_color", models.CharField(blank=True, default="", max_length=20)),
                ("board_size", models.IntegerField(default=8)),
                ("state_json", models.TextField(default="{}")),
                ("seq", models.IntegerField(default=0)),
                ("winner", models.CharField(blank=True, default="", max_length=10)),
                (
                    "win_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
