# Generated by Django 6.0.4 on 2026-04-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiles_json', models.TextField(default='[]')),
                ('spare_json', models.TextField(default='{}')),
                ('players_json', models.TextField(default='[]')),
                ('current_turn', models.IntegerField(default=0)),
                ('num_players', models.IntegerField(default=2)),
                ('last_push_json', models.TextField(default='null')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
